export const KEY = {
  map: 'map',
  texture: {
    tileset: {
      exterior: 'exterior',
      interior: 'interior',
      houseDetails: 'houseDetails',
      pines: 'pines',
      groundGrassDetails: 'groundGrassDetails',
    },
    spritesheet: {
      exteriorAsSheet: 'exteriorAsSheet',
      player: 'player',
      chimney: 'chimney',
      trees: 'trees',
      cat: 'cat',
      birdFly: 'birdFly',
      birdJump: 'birdJump',
      cattle: 'cattle',
    },
    layer: {
      path: 'path',
      road: 'road',
      grassTerrain: 'grassTerrain',
      grass: 'grass',
      forest: 'forest',
      stoneCircleBelowPlayer: 'stoneCircleBelowPlayer',
      stoneCircleAbovePlayer: 'stoneCircleAbovePlayer',
      stoneCircleStumpBelowPlayer: 'stoneCircleStumpBelowPlayer',
      stoneCircleStumpAbovePlayer: 'stoneCircleStumpAbovePlayer',
      mushrooms: 'mushrooms',
      flowerField: 'flowerField',
      gardenDirt: 'gardenDirt',
      gardenPlants: 'gardenPlants',
      wellBelowPlayer: 'wellBelowPlayer',
      wellAbovePlayer: 'wellAbovePlayer',
      fence: 'fence',
      tiles: 'tiles',
      house: 'house',
      decorationNonCollidingBelowPlayer: 'decorationNonCollidingBelowPlayer',
      decorationNonCollidingAbovePlayer: 'decorationNonCollidingAbovePlayer',
      decorationColliding: 'decorationColliding',
      roof: 'roof',
      natureDecorations: 'natureDecorations',
      mapEdgeGrass: 'mapEdgeGrass',
      animals: 'animals',
      areaMarker: 'areaMarker',
      mailboxBelowPlayer: 'mailboxBelowPlayer',
      mailboxAbovePlayer: 'mailboxAbovePlayer',
    },
  },
  audio: {
    backgroundMusic: 'backgroundMusic'
  },
  area: {
    house: 'house',
    well: 'well',
    mushroom: 'mushroom',
    flowers: 'flowers',
    stones: 'stones',
    mailbox: 'mailbox',
    country: 'country',
  },
  text: {
    prompt: 'prompt',
  },
  button: {
    muteMusic: 'muteMusic',
    muteSounds: 'muteSounds',
    restart: 'restart',
  }
} as const;
